### PR TITLE
Update .prow.yaml

### PR DESCRIPTION
**Pull request by stefwrite**
Disabled the Prow test since this isn't a Kubernetes repo (it's just Jupyter Notebook and Jupyter Book content).

### CODE REVIEW

**Comment by HumairAK** [comment]
/lgtm 

(a pr needs at least 1 lgtm and 1 aprpover to merge)

**Comment by HumairAK** [comment]
@harshad16 why is tide not working here?

**Comment by harshad16** [comment]
this seems to be issue with api rate limiting in prow
feel free to manually merge this pr , if tide doesn't merge it in few mins. @HumairAK

**Comment by HumairAK** [comment]
@stefwrite I've also created: https://github.com/operate-first/common/pull/62/files 
this will create a new `training` team, of which you will be a member of, anyone in this team will have admin rights to this repo, so you may manually merge if CI is serving as a blocker.

**Pull request merged**
