### PR TITLE
fixing links, updating logo in training

### LINKED ISSUE #16: Operate First Community - Broken link for "Operate First Community Handbook"
Found a broken link while reading about Operate First. 

Here's the page:
[Check out the Operate First Community Handbook](https://www.operate-first.cloud/community-handbook/)
OF_broken_link

Which results in an error:
OF_broken_link_error

### PR DESCRIPTION
**Pull request by schwesig**
fixes https://github.com/operate-first/training/issues/16

### CODE REVIEW

**Comment by schwesig** [comment]
locally tested, screenshots in next comment

**Comment by schwesig** [comment]
image

**Comment by schwesig** [comment]
image

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
