### PR TITLE
Set up a basic structure for the training repository

### PR DESCRIPTION
**Pull request by stefwrite**
I have completed the initial setup and establishing an organizational structure for this training repository. I will continue work developing content, but I wanted to make sure the upstream repository has these changes so we can start developing some CI/CD for generating and publishing the prototype Jupyter Book that I've staged under modules/skills-professional/agile_basics_and_framework/.

### CODE REVIEW

**Comment by stefwrite** [comment]
I'm new to this process and I'm not sure what I may be missing in my OWNERS file to complete this PR. Please advise.

**Comment by HumairAK** [comment]
@stefwrite you need to join the org :) 

You can do this via a PR here: https://github.com/operate-first/common/blob/main/docs/add_gh_member_and_access.md#become-a-github-member

Once merged you'll get an invitate to the org. Once accepted..that notice will get resolved, after re verifying.

**Comment by stefwrite** [comment]
I resolved the issue with being in the org as per this PR #60 on the common repo: https://github.com/operate-first/common/pull/60

Review requests are still pending. Please advise if there is anything else I need to do for this PR or if I should close it and open a new one.

**Comment by HumairAK** [comment]
> Review requests are still pending. Please advise if there is anything else I need to do for this PR or if I should close it and open a new one. 

@stefwrite to clarify, to get a PR merged a pr needs at least one `/lgtm` and one `/approve`, people in the `reviewers` list can do `/lgtm` while people in the `approvers` list can do `/lgtm` and `/approve`. This is decided by [this list](https://github.com/operate-first/training/blob/main/OWNERS).

General flow is: 
- reviewers review the content, and they give their okay with `/lgtm` 
- approvers have final say in if a PR gets merged, and they acknowledge a pr should be merged by typing `/approve` 

once a pr is `/lgtm` and `/approve`, it _should_ auto merge. 

After this PR is merged, you should be able to do `/approve` as you are now in the owners list.

**Pull request merged**
