### PR TITLE
Updated basic structure in the repository in preparation for adding training content

### PR DESCRIPTION
**Pull request by stefwrite**
This repository is still in its early stages, but I wanted to make sure everything we had so far was pulled back into the OF community repo before we continue developing the first two pieces of training.

### CODE REVIEW

**Comment by stefwrite** [comment]
I'm a bit confused as to why this repo is triggering testing at this stage since I haven't brought it to the community of what kind of build process is needed for this type of content.

**Comment by HumairAK** [comment]
@stefwrite these are tests that are enabled on all repos in the operate first org that are templated using [this repo](https://github.com/operate-first/template).  Some general linting tests are enabled by default. For instance, it will fail if you have unnecessary whitespace, or if you are missing EOF newlines. These are enabled by the prow presubmit job defined [here](https://github.com/operate-first/training/blob/main/.prow.yaml#L4). You can see there is a `pre-commit` test, configurations for this test are [here](https://github.com/operate-first/training/blob/main/.pre-commit-config.yaml). 

If you do not want to have these for this repo. You can remove the presubmit test defined [here](https://github.com/operate-first/training/blob/main/.prow.yaml). If you do it in this PR I _think_ it should take affect from this PR and not run the test.

**Comment by stefwrite** [comment]
I've corrected the issue that caused the build to fail here, but it doesn't look like the bot re-engaged after the new commit. I'll just cancel this request and open a new one.

**Pull request closed without merging**
